# Default configuration

attn_head_set: "8-21,8-14,7-22,6-31,8-28,10-26,10-0,5-5,8-3,6-30,8-0,7-26,7-25,7-23,11-4,8-20" # top16
model_base_class: "Llama-3.2-1B-Instruct"
model_name_or_path: "meta-llama/Llama-3.2-1B-Instruct"